import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useAuthState } from "react-firebase-hooks/auth";
import { useCollection } from "react-firebase-hooks/firestore"
import { auth, firestore } from 'firebase/clientApp';
import Link from 'next/link';
import Button from "@mui/material/Button"
import { useState } from 'react';
import CreateEvent from 'components/createEvent';

export default function Home() {
  const [user, loading, error] = useAuthState(auth);

  const [Events, EventsLoading, EventsError] = useCollection(
    firestore.collection('Events'),
    {}
  )

  const [showCreateEventForm, toggleNewEventForm] = useState(false)

  return (
    <div className="app">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="hero">
          <h2>Events</h2>

          <div className="events">
            {!EventsLoading && Events && Events.docs.map((doc) => {
              const { title, location } = doc.data()

              return (
                <div key={doc.id} className="event card">
                  <Link href={`/events/${doc.id}`}>
                    <a>
                      <p>{title}</p>
                      <p>{location}</p>
                    </a>
                  </Link>
                </div>
              )
            })}
          </div>

          <Button onClick={() => toggleNewEventForm(!showCreateEventForm)}>Create New Event</Button>
          {showCreateEventForm && (
            <CreateEvent />
          )}
        </div>
      </main>

      <footer className={styles.footer}>
          Jacob Benaim ©
      </footer>
    </div>
  )
}
